/**
 * Generates src/styles/fonts.css from every font file inside public/fonts/<folder>/.
 * For each file it emits an @font-face rule and a `.font-brand-<variant>` class
 * (e.g. SupremeLLTT-BoldFlat.woff2 -> .font-brand-bold-flat).
 *
 * Run `npm run generate-fonts` after adding or removing font files.
 */
import fs from "node:fs";
import path from "node:path";

const fontsDir = path.resolve("public/fonts");
const outputCssPath = path.resolve("src/styles/fonts.css");

const generateFontFace = (fontName, folderName, filename, extension) => {
  const formatType = extension === "ttf" ? "truetype" : extension;
  return `@font-face { font-family: '${fontName}'; src: url('/fonts/${folderName}/${filename}') format('${formatType}'); }`;
};

const generateFontFamilyClassName = (fontName) => {
  const fontId = fontName
    .split("-")[1]
    .replace(/([a-z])([A-Z])/g, "$1-$2") // insert hyphen between camelCase transitions
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2") // handle ALLCAPS-to-Camel transitions
    .toLowerCase();

  return `.font-brand-${fontId} { font-family: '${fontName}', 'sans-serif'; }`;
};

if (!fs.existsSync(fontsDir)) {
  console.error('No "public/fonts" directory found. Exiting...');
  process.exit(1);
}

const rules = [];

const subfolders = fs
  .readdirSync(fontsDir, { withFileTypes: true })
  .filter((dirent) => dirent.isDirectory() && !dirent.name.startsWith("."))
  .map((dirent) => dirent.name);

for (const folderName of subfolders) {
  for (const file of fs.readdirSync(path.join(fontsDir, folderName))) {
    const extension = path.extname(file).slice(1);
    if (!["woff2", "woff", "ttf", "otf"].includes(extension)) continue;

    const fontName = path.basename(file, `.${extension}`);
    rules.push(generateFontFace(fontName, folderName, file, extension));
    rules.push(generateFontFamilyClassName(fontName));
  }
}

fs.writeFileSync(
  outputCssPath,
  `/* Generated by scripts/generate-fonts.mjs - do not edit by hand. */\n${rules.join("\n")}\n`,
);

console.log(`Generated ${rules.length / 2} fonts in ${path.relative(process.cwd(), outputCssPath)}`);
